### PR TITLE
Modernize rust-hawk.

### LINKED ISSUE #15: Switch to a newer error-handling mechanism than error_chain
Even with error_chain 0.12.0 (the latest):

```
warning: use of deprecated item 'std::error::Error::cause': replaced by Error::source, which can support downcasting
  --> src/error.rs:1:1
   |
1  | / error_chain! {
2  | |     errors {
3  | |         HeaderParseError {
4  | |             description("Unparseable Hawk header")
...  |
11 | |     }
12 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

### LINKED ISSUE #17: Upgrade to Rust 2018

### PR DESCRIPTION
**Pull request by thomcc**
- Update to Rust 2018 (fixes #17)
- Replace error_chain with failure. (fixes #15)
- Replace `time` (which is deprecated) with `std::time`
- Update other dependency versions.

Also cleaned up error handling some (and header parsing as a result), and did some minor optimizations.

I did this before checking your issue list, sorry for stepping on your toes with #17/#15, I kind of had still been under the assumption that the maintenance on this crate was quite passive.

Caveat: I don't really understand HAWK deeply, so I'm mostly relying on tests to catch mistakes. That said, the changes are almost all mechanical.

Note: this is a breaking change, so you'll want to bump the major version. In practice the breaking changes are that new error kinds were added, and Timespec was replaced with SystemTime.

### CODE REVIEW

**Comment by djmitche** [comment]
Wow, thanks!  I will have a look.  I don't mind at all, of course -- working on software with other people is always better, and will surely improve my Rust skills.

**Comment by thomcc** [comment]
It's no problem. In the nearish future we're (mozilla/application-services) going to try to make the crypto more easily replaceable so that we can swap in NSS (under a feature, of course). I took a look to familiarize myself with the code, and realized it was in need of some attention.

File: src/mac.rs [hunk 1]
```diff
@@ -32,32 +32,40 @@ impl Mac {
...
-        writeln!(buffer, "{}", path)?;
-        writeln!(buffer, "{}", host)?;
-        writeln!(buffer, "{}", port)?;
+        // Note: there's a \n after each item.
+        let mut buffer: Vec<u8> = Vec::with_capacity(
+            15 + 1 + // mac_type (worst case since it doesn't really matter)
+            10 + 1 + // ts (in practice this will be 10 bytes)
+            nonce.len() + 1 +
+            host.len() + 1 +
+            6 + 1 + // Longer than 6 bytes fo port seems very unlikely
```
Comment (djmitche) [inline src/mac.rs]: (typo)

File: src/bewit.rs [hunk 2]
```diff
@@ -35,10 +35,11 @@ impl<'a> Bewit<'a> {
 
     /// Generate the fully-encoded string for this Bewit
     pub fn to_str(&self) -> String {
+        use base64::display::Base64Display;
```
Comment (djmitche) [inline src/bewit.rs:37]: why embed this in the function, rather than toplevel?

**Review by djmitche — APPROVED** [review]
Looks good, and I learned a thing or two :)

**Comment by djmitche** [comment]
well, I guess "changes requested" but just the typo -- then I'll merge :)

File: src/bewit.rs (hunk 2 above)
Comment (thomcc) [reply src/bewit.rs:37]: Nothing else really needed it. If you'd prefer I move it I can.

Comment (djmitche) [reply src/bewit.rs:37]: Just trying to get a sense for proper style.  In other languages the equivalents (import, require, etc.) go at the top unless there's some special need to delay the load or scope the symbols.  If this seems normal to you then I'm happy with it :)

**Comment by djmitche** [comment]
Would you like me to cut a release?

**Comment by thomcc** [comment]
Yes, that would be great.

**Comment by djmitche** [comment]
v2.0.0
